### PR TITLE
feat: add parameters api into PlutoStaticDataset

### PR DESCRIPTION
**Pull request by xshaokun**
For now I only added the API into PlutoStaticDataset

### CODE REVIEW

**Comment by xshaokun** [comment]
Due to the opinion from https://github.com/neutrinoceros/yt_idefix/pull/209#issuecomment-1449776183, I suspend this PR for now.

**Comment by neutrinoceros** [comment]
Wouldn't this make more sense as a PR on the original repo rather than this fork ?

**Comment by xshaokun** [comment]
> Wouldn't this make more sense as a PR on the original repo rather than this fork ?

That's true. I was just not sure if you are willing to accept this API for IdefixVtkDataset when I opened this PR, so I added it as experimental. Besides it’s not urgent.

**Comment by dutta-alankar** [comment]
@xshaokun By the time I checked that you pulled this PR, I had already written this. So, this now has a conflict. Will it be okay if I close this PR?

**Comment by xshaokun** [comment]
> @xshaokun By the time I checked that you pulled this PR, I had already written this. So, this now has a conflict. Will it be okay if I close this PR?

Sure. Go ahead.

**Pull request closed without merging**
